# docker run --restart always --name babelfishpg -d -p 1433:1433 -p 5432:5432 jonathanpotts/babelfishpg -u db-username -p db-userpassword
version: '3.8'
services:
  pg:
    container_name: babelfishpg
    # 用原作者隻 docker image
    image: jonathanpotts/babelfishpg:latest
    # 或者用原作者啲 code 自己 build 一隻 image
    # build: .
    # image: my/babelfishpg
    restart: always
    ports:
      - '1433:1433'
      - '5432:5432'
    entrypoint: ["/start.sh", "-u", "db-username", "-p", "db-userpassword"]
